// elephants
export const FETCH_ELEPHANTS_REQUEST = 'FETCH_ELEPHANTS_REQUEST';
export const FETCH_ELEPHANTS_SUCCESS = 'FETCH_ELEPHANTS_SUCCESS';
export const FETCH_ELEPHANTS_FAILURE = 'FETCH_ELEPHANTS_FAILURE';

// menu
export const CHANGE_LIST = 'CHANGE_LIST';